file_format: "1"
id: mango
name: Mango
type: shield
url: N/A
requires: [wireless_pro_micro]
features:
  - keys
  - display
  - underglow
  - rgb
  - 5-way switch
siblings:
  - mango_left
  - mango_right